# Data Preparation Workflow

In [ ]:
!pip install pandas scikit-learn

Requirement already satisfied: pandas in c:\users\chari\onedrive\desktop\ece\ing4\apprentissage_estimation_baysien\.venv\lib\site-packages (2.3.3)

ERROR: Could not find a version that satisfies the requirement sckit-learn (from versions: none)
ERROR: No matching distribution found for sckit-learn

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

- charger les données en DataFrame

In [2]:
path = input("Entrer le chemin du dataset CSV.")

if not path.endswith('.csv') or not path:
    path = "../data/movies.csv"

In [18]:
dataframe = pd.read_csv(path)

C:\Users\chari\AppData\Local\Temp\ipykernel_12612\3521874628.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  dataframe = pd.read_csv(path)

In [19]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2590932 entries, 0 to 2590931
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   id              object
 1   name            object
 2   year            object
 3   rating          float64
 4   certificate     object
 5   duration        object
 6   genre           object
 7   votes           object
 8   gross_income    object
 9   directors_id    object
 10  directors_name  object
 11  stars_id        object
 12  stars_name      object
 13  description     object
dtypes: float64(1), object(13)
memory usage: 276.7+ MB

In [20]:
dataframe.head(3)

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt4710316,Best in Sex: 2015 AVN Awards,(2015 TV Special),4.0,TV-MA,94 min,"Adult, News",124.0,0,nm1624094,Gary Miller,"nm4766272,nm2670531,nm4920605,nm6284246","Farrah Laurel Abraham,Asa Akira,Anikka Albrite...",The hottest adult stars and top adult movies a...
1,tt1281857,Naughty Novelist,(2008 Video),3.8,Not Certified,88 min,Adult,174.0,0,nm0045256,John Bacchus,"nm0128986,nm1969196,nm0451160,nm6130462","Darian Caine,Jackie Stevens,A.J. Khan,Arrora",Darian is a successful journalist but when she...
2,tt2294954,2011 AVN Awards Show,(2011 TV Special),5.7,Not Certified,83 min,"Adult, News",39.0,0,"nm1624094,nm0754845","Gary Miller,Timothy E. Sabo","nm2200343,nm2670531,nm1267549,nm3585599","Aubrey Addams,Asa Akira,Monique Alexander,Rave...",Add a Plot

- traiter les données : fixer type des données (entiers, flottants, chaînes de caractères)

In [ ]:
# variables explicatives : rating, votes, popularity
dataframe["rating"] = pd.to_numeric(dataframe["rating"], errors='coerce')
dataframe["rating"] = dataframe["rating"].astype(float, errors='ignore')

dataframe["votes"] = pd.to_numeric(dataframe["votes"], errors='coerce')
dataframe["votes"] = dataframe["votes"].astype(float, errors='ignore') # remarque : garder en float pour éviter les problèmes de type lors des calculs

# variable cible : genre

# autres variables :

- traiter les données : valeurs manquantes

In [22]:
# supprimer les lignes avec des valeurs manquantes
print("Nombre de lignes avant suppression des valeurs manquantes :", len(dataframe))
print("Nombre de valeurs manquantes par colonne :")
print(dataframe.isnull().sum())
dataframe.dropna(inplace=True)
print("Nombre de lignes après suppression des valeurs manquantes :", len(dataframe))

Nombre de lignes avant suppression des valeurs manquantes : 2590932
Nombre de valeurs manquantes par colonne :
id                    0
name                  4
year                  0
rating                0
certificate           0
duration              0
genre                 0
votes             43088
gross_income          0
directors_id          0
directors_name        0
stars_id              0
stars_name            0
description           0
dtype: int64
Nombre de lignes après suppression des valeurs manquantes : 2547840

- traiter les données : uniformisation des genres

In [23]:
# uniformiser les genres : garder uniquement le genre principal (le premier genre listé)
print("Genres avant uniformisation :", dataframe['genre'].unique())
dataframe['genre'] = dataframe['genre'].apply(lambda x: x.split(',')[0].strip())
print("Genres après uniformisation :", dataframe['genre'].unique())
dataframe.head(3)

Genres avant uniformisation : ['Adult, News' 'Adult' 'Adult, Romance' ... 'Game-Show, News'
 'Drama, Game-Show' 'Family, Game-Show, News']
Genres après uniformisation : ['Adult' 'Documentary' 'Action' 'Short' 'Animation' 'Crime' 'Comedy'
 'Biography' 'Adventure' 'Drama' 'Horror' 'Thriller' 'Musical' 'Mystery'
 'Fantasy' 'Romance' 'Family' 'Western' 'Sci-Fi' 'Reality-TV' 'Music'
 'News' 'History' 'Game-Show' 'Film-Noir' 'War' 'Talk-Show' 'Sport']

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt4710316,Best in Sex: 2015 AVN Awards,(2015 TV Special),4.0,TV-MA,94 min,Adult,124.0,0,nm1624094,Gary Miller,"nm4766272,nm2670531,nm4920605,nm6284246","Farrah Laurel Abraham,Asa Akira,Anikka Albrite...",The hottest adult stars and top adult movies a...
1,tt1281857,Naughty Novelist,(2008 Video),3.8,Not Certified,88 min,Adult,174.0,0,nm0045256,John Bacchus,"nm0128986,nm1969196,nm0451160,nm6130462","Darian Caine,Jackie Stevens,A.J. Khan,Arrora",Darian is a successful journalist but when she...
2,tt2294954,2011 AVN Awards Show,(2011 TV Special),5.7,Not Certified,83 min,Adult,39.0,0,"nm1624094,nm0754845","Gary Miller,Timothy E. Sabo","nm2200343,nm2670531,nm1267549,nm3585599","Aubrey Addams,Asa Akira,Monique Alexander,Rave...",Add a Plot

- convertir les genres (**valeur prédite**) en format numérique

In [24]:
label_encoder = LabelEncoder()
dataframe['genre_encoded'] = label_encoder.fit_transform(dataframe['genre'])
print("Genres :", dataframe['genre'].unique())
print("Genres encodés :", dataframe['genre_encoded'].unique())

Genres : ['Adult' 'Documentary' 'Action' 'Short' 'Animation' 'Crime' 'Comedy'
 'Biography' 'Adventure' 'Drama' 'Horror' 'Thriller' 'Musical' 'Mystery'
 'Fantasy' 'Romance' 'Family' 'Western' 'Sci-Fi' 'Reality-TV' 'Music'
 'News' 'History' 'Game-Show' 'Film-Noir' 'War' 'Talk-Show' 'Sport']
Genres encodés : [ 1  7  0 22  3  6  5  4  2  8 14 25 16 17 10 20  9 27 21 19 15 18 13 12
 11 26 24 23]

In [25]:
dataframe.head(3)

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description,genre_encoded
0,tt4710316,Best in Sex: 2015 AVN Awards,(2015 TV Special),4.0,TV-MA,94 min,Adult,124.0,0,nm1624094,Gary Miller,"nm4766272,nm2670531,nm4920605,nm6284246","Farrah Laurel Abraham,Asa Akira,Anikka Albrite...",The hottest adult stars and top adult movies a...,1
1,tt1281857,Naughty Novelist,(2008 Video),3.8,Not Certified,88 min,Adult,174.0,0,nm0045256,John Bacchus,"nm0128986,nm1969196,nm0451160,nm6130462","Darian Caine,Jackie Stevens,A.J. Khan,Arrora",Darian is a successful journalist but when she...,1
2,tt2294954,2011 AVN Awards Show,(2011 TV Special),5.7,Not Certified,83 min,Adult,39.0,0,"nm1624094,nm0754845","Gary Miller,Timothy E. Sabo","nm2200343,nm2670531,nm1267549,nm3585599","Aubrey Addams,Asa Akira,Monique Alexander,Rave...",Add a Plot,1

In [26]:
print(dataframe[["rating", "votes"]].dtypes)
print(dataframe[["rating", "votes"]].head())

rating    float64
votes     float64
dtype: object
   rating  votes
0     4.0  124.0
1     3.8  174.0
2     5.7   39.0
3     4.9  225.0
4     6.7  101.0

- créer la feature **popularité** selon les critères suivants :
    + technique `somme pondérée` : *votes* x *rating*

In [28]:
dataframe["popularity"] = dataframe["rating"] * dataframe["votes"]
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2547840 entries, 0 to 2590931
Data columns (total 16 columns):
 #   Column          Dtype
---  ------          -----
 0   id              object
 1   name            object
 2   year            object
 3   rating          float64
 4   certificate     object
 5   duration        object
 6   genre           object
 7   votes           float64
 8   gross_income    object
 9   directors_id    object
 10  directors_name  object
 11  stars_id        object
 12  stars_name      object
 13  description     object
 14  genre_encoded   int64
 15  popularity      float64
dtypes: float64(3), int64(1), object(12)
memory usage: 330.5+ MB